---
# Syncs groups / gids on the cluster
- name: Update user groups
  group: name={{ item.name }} gid={{ item.uid }} state=present
  with_items: ssh_users
  tags:
    - usermod

- name: Update other groups
  group: name={{ item.name }} gid={{ item.gid }} state=present
  with_items: cluster_groups
  tags:
    - usermod
